# Generated by Django 4.2.7 on 2025-09-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='頭像URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='oauth_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='OAuth ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='oauth_provider',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google')], default='email', max_length=10, verbose_name='登入方式'),
        ),
    ]
