# Generated by Django 4.2.7 on 2025-08-29 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('hiragana', '平假名'), ('katakana', '片假名'), ('mixed', '混合練習')], max_length=20, verbose_name='練習類型')),
                ('categories', models.JSONField(default=list, help_text='例：["basic", "dakuten", "handakuten", "youon"]', verbose_name='練習類別')),
                ('total_questions', models.PositiveIntegerField(verbose_name='總題數')),
                ('correct_answers', models.PositiveIntegerField(verbose_name='答對題數')),
                ('accuracy_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='正確率')),
                ('duration_seconds', models.PositiveIntegerField(verbose_name='練習時長(秒)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='開始時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '練習記錄',
                'verbose_name_plural': '練習記錄',
                'db_table': 'practice_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_kana', models.CharField(max_length=10, verbose_name='題目假名')),
                ('correct_romaji', models.CharField(max_length=20, verbose_name='正確羅馬拼音')),
                ('user_answer', models.CharField(max_length=20, verbose_name='使用者答案')),
                ('is_correct', models.BooleanField(verbose_name='是否正確')),
                ('response_time_ms', models.PositiveIntegerField(verbose_name='回答時間(毫秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='答題時間')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_records', to='practice.practicesession', verbose_name='練習記錄')),
            ],
            options={
                'verbose_name': '答題記錄',
                'verbose_name_plural': '答題記錄',
                'db_table': 'answer_records',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kana_type', models.CharField(choices=[('hiragana', '平假名'), ('katakana', '片假名')], max_length=20, verbose_name='假名類型')),
                ('category', models.CharField(choices=[('basic', '基本音'), ('dakuten', '濁音'), ('handakuten', '半濁音'), ('youon', '拗音')], max_length=20, verbose_name='練習類別')),
                ('total_attempts', models.PositiveIntegerField(default=0, verbose_name='總嘗試次數')),
                ('correct_attempts', models.PositiveIntegerField(default=0, verbose_name='答對次數')),
                ('accuracy_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='正確率')),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True, verbose_name='最後練習時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_statistics', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '學習統計',
                'verbose_name_plural': '學習統計',
                'db_table': 'learning_statistics',
                'unique_together': {('user', 'kana_type', 'category')},
            },
        ),
    ]
